### ISSUE TITLE
スポンサー向け案内文の作成

### ISSUE THREAD

**Issue by matyuda** [jaws-ug-kanazawa/20231209withAWSStartupCommunity#1]

**Comment by PharaohKJ** [comment]
登壇内容を仮でいいので埋める。

**Comment by PharaohKJ** [comment]
@koseizakio ↑よろしく

**Comment by koseizakio** [comment]
スタートアップ企業の創業10年以内で、AWS Activateを利用して良かったことなどのライトニングトークネタがある企業さんを講演を呼べるといいですね。

https://aws.amazon.com/jp/activate/

**Comment by matyuda** [comment]
情報白書から見るパブリッククラウドの動向
https://www.soumu.go.jp/johotsusintokei/whitepaper/ja/r05/html/datashu.html#f00246

**Comment by matyuda** [comment]
現時点での案内文
https://github.com/jaws-ug-kanazawa/20231209withAWSStartupCommunity/blob/main/%E5%AE%A3%E4%BC%9D%E7%94%A8%E3%83%81%E3%83%A9%E3%82%B7.pdf

#6 の内容をふまえて見直すこととなった

**Comment by matyuda** [comment]
@PharaohKJ さんにて8/末までで巻き取っていただくことになったため、担当とマイルストーンを変更しました。

**Comment by matyuda** [comment]
@PharaohKJ 
9/5に商工会議所へ説明する機会いただきましたので、それまでにリニューアル版案内文があると嬉しいです。
