### ISSUE TITLE
ロジスティクス表作成

### ISSUE THREAD

**Issue by matyuda** [jaws-ug-kanazawa/20231209withAWSStartupCommunity#13]

**Comment by matyuda** [comment]
作成済みの状況で、必要に応じて追加していく

**Comment by PharaohKJ** [comment]
担当つけてほしいんだけど無理？

**Comment by matyuda** [comment]
担当は小西さんにお願いしてあります。
当日の担当を想定していますが、それよりも前にお願いしておくことがありましたらご指摘ください。

**Comment by PharaohKJ** [comment]
当日よりも前に、何が誰用意してどこに運び込むかとかまとめてほしい。現状足りてる・足りてない含めてチェックお願いしたい。

**Comment by matyuda** [comment]
ロジスティクス表に書出しはしていますが、未発注分が分かりづらいので整理して、小西さんと共有するようにします。

**Comment by matyuda** [comment]
未発注分を明確にして対応済み
