### ISSUE TITLE
懇親会飲み物の手配

### ISSUE THREAD

**Issue by matyuda** [jaws-ug-kanazawa/20231209withAWSStartupCommunity#14]
乙村酒類販売が本日やっていなかった。
近隣の金丸酒店はビールを取り扱っていなかった

**Comment by matyuda** [comment]
乙村酒類販売さんは一元での配送は断っているとのことにつき、庄田酒販さんに依頼中
https://shodashuhan.com/sake/572

**Comment by PharaohKJ** [comment]
スポンサー候補にお願いしているところ

**Comment by matyuda** [comment]
スポンサー候補からは名札と飲み物のどちらのご承諾をいただけている状況ですか？

**Comment by matyuda** [comment]
@PharaohKJ 
↑メンション付け忘れていました

お手すきの時に教えてください

**Comment by PharaohKJ** [comment]
@matyuda お酒スポンサー、だそうです。領収書・支払いともに会場で行うそうで、配達までの手配よろしくお願いします。
領収書の宛名は ラバジャバシステム株式会社 で　いただきたいとのこと。

**Comment by matyuda** [comment]
@PharaohKJ 
お返事遅くなりました。承知しました。

食事については芝寿司さんへ仮数量を連絡済みです。

**Comment by matyuda** [comment]
芝寿しさん発注済み

12/7にお酒の注文完了次第、本件クローズ

**Comment by matyuda** [comment]
12/7にお酒の注文完了済
回収は翌日庄田酒販さんへ持ち込み予定
