### ISSUE TITLE
講演会時のテーブルレイアウト表作成

### ISSUE THREAD

**Issue by matyuda** [jaws-ug-kanazawa/20231209withAWSStartupCommunity#15]

**Comment by matyuda** [comment]
たたき台
[レイアウト図.xlsx](https://github.com/jaws-ug-kanazawa/20231209withAWSStartupCommunity/files/13403419/default.xlsx)

**Comment by PharaohKJ** [comment]
受付は中に設置してくれって話じゃなかったっけ。
6F貸切ならいいんだっけ。

2023年11月19日(日) 22:53 Yasuhiro Matsuda ***@***.***>:

**Comment by matyuda** [comment]
6F貸切の場合には、受付を中に設置しなくて良いとお話でした。
(AWS Community Dayでも受付は通路でしたので実績もあります)

**Comment by matyuda** [comment]
一旦確定済み
必要に応じて修正する
