### ISSUE TITLE
2次会会場を探す

### ISSUE THREAD

**Issue by matyuda** [jaws-ug-kanazawa/20231209withAWSStartupCommunity#16]
21時30分ごろからやっているお店を探す

**Comment by PharaohKJ** [comment]
酒飲むだけなら https://www.ipzowie.com とか

**Comment by matyuda** [comment]
駅前に近くていいですね！

**Comment by matyuda** [comment]
@PharaohKJ 
お店への予約をお願いできますか？
直前でも大丈夫そうでしたら帰国後の12/4に予約しようと思います。

**Comment by PharaohKJ** [comment]
zowieさんはキャッシュオンのお店で予約とかなかったはず

**Comment by matyuda** [comment]
@PharaohKJ 
登壇者の方には、当日2次会の予定があることをあわせてお伝えしておきますね。

**Comment by matyuda** [comment]
@PharaohKJ 
南町近辺で予約できそうなお店が見つかりそうです。予約できましたら変更するようにします。

**Comment by matyuda** [comment]
22:15～で予約済み
９日22時15分〜お一人当たり 3,000円2時間飲み放題、チャーム付き。10名。
一名位なら増減あっても連絡不要です。マスター堀川明広さん　です。
https://www.google.com/maps/place/%E7%A5%9E%E7%A4%BEBar+HOLY/@36.5712778,136.6539227,15z/data=!4m6!3m5!1s0x5ff83305626bce75:0x1cee537059cbd63f!8m2!3d36.5712778!4d136.6539227!16s%2Fg%2F11h42nz_5m?hl=ja&entry=ttu
