### ISSUE TITLE
パーティションを途中で取り外せるか確認する

### ISSUE THREAD

**Issue by matyuda** [jaws-ug-kanazawa/20231209withAWSStartupCommunity#3]
懇親会より交流室１，２のパーティションを取り外す想定だが、AWS Community Day Kanazawaと同じように途中で外せるかをITプラザ武蔵へ確認する。

**Comment by PharaohKJ** [comment]
これ途中で外してもらうのむずかしいから、仕切ったままで、椅子を隣の部屋からもってきて対応してたような記憶もある。

**Comment by matyuda** [comment]
たしかにそうだったかもしれませんね。

仕切ったままの前提としましょうか。
だとすれば、懇親会準備（30分間）はトラック2のみでおこなって、トラックAは1セッション追加できそうですね。

**Comment by PharaohKJ** [comment]
今日、電話しておきます。

**Comment by PharaohKJ** [comment]
電話した。折り返し待ち。

**Comment by matyuda** [comment]
確認いただき、ありがとうございます。
結果分かりましたら追記をお願いいたします。

**Comment by PharaohKJ** [comment]
パーティションの移動のために、30分ほしいとのこと。
その間に部屋の中からも出てもらわないといけないし、ちょっとやめておいたほうがよさそうですね。

**Comment by matyuda** [comment]
承知しました。
パーティション取り外ししなくても良いようにタイムテーブル変更します。
